### ISSUE TITLE
NameError: name 'FlexiCubes' is not defined

### ISSUE THREAD

**Issue by ddddddeyrueuad** [if-ai/ComfyUI-IF_Trellis#19]
Model path after ensuring existence: D:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\models\checkpoints\TRELLIS-image-large
Path exists: True
Loading local model: ss_dec_conv3d_16l8_fp16
Loading local model: ss_flow_img_dit_L_16l8_fp16
Loading local model: slat_dec_gs_swin8_B_64l8gs32_fp16
Loading local model: slat_dec_rf_swin8_B_64l8r16_fp16
Loading local model: slat_dec_mesh_swin8_B_64l8m256c_fp16
Error loading TRELLIS model: name 'FlexiCubes' is not defined
!!! Exception during processing !!! name 'FlexiCubes' is not defined
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\IF_TrellisCheckpointLoader.py", line 164, in load_model
    pipeline = TrellisImageTo3DPipeline.from_pretrained(str(self.model_path))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\pipelines\trellis_image_to_3d.py", line 58, in from_pretrained
    pipeline = super(TrellisImageTo3DPipeline, TrellisImageTo3DPipeline).from_pretrained(path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\pipelines\base.py", line 41, in from_pretrained
    k: models.from_pretrained(os.path.join(path, v))
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\models\__init__.py", line 69, in from_pretrained
    model = create_model_from_config(config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\models\__init__.py", line 104, in create_model_from_config
    return model_class(**args)
           ^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\models\structured_latent_vae\decoder_mesh.py", line 105, in __init__
    self.mesh_extractor = SparseFeatures2Mesh(res=self.resolution*4, use_color=self.rep_config.get('use_color', False))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\representations\mesh\cube2mesh.py", line 76, in __init__
    self.mesh_extractor = FlexiCubes(device=device)
                          ^^^^^^^^^^
NameError: name 'FlexiCubes' is not defined

**Comment by QuintessentialForms** [comment]
I fixed this by manually installing `gradio_litmodel3d==0.0.1`.
Now my gen fails for a completely different error, but at least FlexiCubes is not the problem.

**Comment by if-ai** [comment]
what error you are getting?
also that gradio_litmodel3d should have not stop flexicubes that's a gradio component and comfy does not use gradio at all

**Comment by if-ai** [comment]
the flexicubes error was a typo I made on the import it I added an 's' instead of flexicube I was importing FlexiCubes

**Comment by QuintessentialForms** [comment]
> what error you are getting? also that gradio_litmodel3d should have not stop flexicubes that's a gradio component and comfy does not use gradio at all

Well, maybe you are right. Maybe the error went away after a pull request, and I only thought that it went away because of that install. :-/
Currently, my ComfyUI installation has been completely bricked with dozens of incompatible libraries, including scipy, xformers, and kaolin, which are all serious.
I am left with no choice but to reinstall Comfy in a new environment from scratch.
