### ISSUE TITLE
No module named 'diff_gauss'

### ISSUE THREAD

**Issue by gsgoldma** [if-ai/ComfyUI-IF_Trellis#20]
was working well a couple of  days ago? maybe i updated something, but now im getting this error:

got prompt
Model path after ensuring existence: D:\Automatic Models\models\checkpoints\TRELLIS-image-large
Path exists: True
Loading local model: ss_dec_conv3d_16l8_fp16
[SPARSE][CONV] spconv algo: native
Loading local model: ss_flow_img_dit_L_16l8_fp16
[ATTENTION] Using backend: flash_attn
Loading local model: slat_dec_gs_swin8_B_64l8gs32_fp16
Loading local model: slat_dec_rf_swin8_B_64l8r16_fp16
Loading local model: slat_dec_mesh_swin8_B_64l8m256c_fp16
Loading local model: slat_flow_img_dit_L_64l8p2_fp16
Using cache found in C:\Users\grego/.cache\torch\hub\facebookresearch_dinov2_main
UserWarning: xFormers is available (SwiGLU)
UserWarning: xFormers is available (Attention)
UserWarning: xFormers is available (Block)
using MLP layer as FFN
Initializing rembg session...
Sampling: 100%|████████████████████████████████████████████████████████████████████████| 12/12 [00:01<00:00,  6.11it/s]
Sampling: 100%|████████████████████████████████████████████████████████████████████████| 12/12 [00:02<00:00,  4.38it/s]
Rendering: 0it [00:00, ?it/s]
Error in image_to_3d: No module named 'diff_gauss'
Traceback (most recent call last):
  File "D:\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\IF_Trellis.py", line 221, in image_to_3d
    video_frames = render_utils.render_video(outputs['gaussian'][0])['color']
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\utils\render_utils.py", line 96, in render_video
    return render_frames(sample, extrinsics, intrinsics, {'resolution': resolution, 'bg_color': bg_color}, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\utils\render_utils.py", line 73, in render_frames
    res = renderer.render(sample, extr, intr, colors_overwrite=colors_overwrite)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\renderers\gaussian_render.py", line 220, in render
    render_ret = render(camera_dict, gausssian, self.pipe, self.bg_color, override_color=colors_overwrite, scaling_modifier=self.pipe.scale_modifier)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\renderers\gaussian_render.py", line 58, in render
    from diff_gauss import GaussianRasterizer, GaussianRasterizationSettings
ModuleNotFoundError: No module named 'diff_gauss'

!!! Exception during processing !!! No module named 'diff_gauss'
Traceback (most recent call last):
  File "D:\ComfyUI\execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\micromamba\envs\trellis\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\IF_Trellis.py", line 221, in image_to_3d
    video_frames = render_utils.render_video(outputs['gaussian'][0])['color']
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\utils\render_utils.py", line 96, in render_video
    return render_frames(sample, extrinsics, intrinsics, {'resolution': resolution, 'bg_color': bg_color}, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\utils\render_utils.py", line 73, in render_frames
    res = renderer.render(sample, extr, intr, colors_overwrite=colors_overwrite)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\renderers\gaussian_render.py", line 220, in render
    render_ret = render(camera_dict, gausssian, self.pipe, self.bg_color, override_color=colors_overwrite, scaling_modifier=self.pipe.scale_modifier)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\renderers\gaussian_render.py", line 58, in render
    from diff_gauss import GaussianRasterizer, GaussianRasterizationSettings
ModuleNotFoundError: No module named 'diff_gauss'

**Comment by gsgoldma** [comment]
I had to reinstall diff_gaussian_rasterization, but i also had to download the glm to thirdparty/user since that was empty for some reason. maybe that was the issue.
