### ISSUE TITLE
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1374x384 and 1024x2048)

### ISSUE THREAD

**Issue by gsgoldma** [if-ai/ComfyUI-IF_Trellis#22]
[30a7776](https://github.com/if-ai/ComfyUI-IF_Trellis/commit/30a7776b82bbeb7df943e13319f850d9ac8afc12)

this happens after it loads the model and is done sampling: 

!!! Exception during processing !!! mat1 and mat2 shapes cannot be multiplied (1374x384 and 1024x2048)
Traceback (most recent call last):
  File "D:\ComfyUI\execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\micromamba\envs\trellis\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\IF_Trellis.py", line 311, in image_to_3d
    outputs = model.run(pil_imgs[0], **pipeline_params)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\micromamba\envs\trellis\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\pipelines\trellis_image_to_3d.py", line 408, in run
    coords = self.sample_sparse_structure(cond, num_samples, sparse_structure_sampler_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\micromamba\envs\trellis\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\pipelines\trellis_image_to_3d.py", line 285, in sample_sparse_structure
    z_s = self.sparse_structure_sampler.sample(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\micromamba\envs\trellis\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\pipelines\samplers\flow_euler.py", line 199, in sample
    return super().sample(model, noise, cond, steps, rescale_t, verbose, neg_cond=neg_cond, cfg_strength=cfg_strength, cfg_interval=cfg_interval, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\micromamba\envs\trellis\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\pipelines\samplers\flow_euler.py", line 112, in sample
    out = self.sample_once(model, sample, t, t_prev, cond, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\micromamba\envs\trellis\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\pipelines\samplers\flow_euler.py", line 73, in sample_once
    pred_x_0, pred_eps, pred_v = self._get_model_prediction(model, x_t, t, cond, **kwargs)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\pipelines\samplers\flow_euler.py", line 43, in _get_model_prediction
    pred_v = self._inference_model(model, x_t, t, cond, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\pipelines\samplers\guidance_interval_mixin.py", line 11, in _inference_model
    pred = super()._inference_model(model, x_t, t, cond, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\pipelines\samplers\flow_euler.py", line 40, in _inference_model
    return model(x_t, t, cond, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\micromamba\envs\trellis\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\micromamba\envs\trellis\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\models\sparse_structure_flow.py", line 192, in forward
    h = block(h, t_emb, cond)
        ^^^^^^^^^^^^^^^^^^^^^
  File "D:\micromamba\envs\trellis\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\micromamba\envs\trellis\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\modules\transformer\modulated.py", line 156, in forward
    return self._forward(x, mod, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\modules\transformer\modulated.py", line 143, in _forward
    h = self.cross_attn(h, context)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\micromamba\envs\trellis\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\micromamba\envs\trellis\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\modules\attention\modules.py", line 134, in forward
    kv = self.to_kv(context)
         ^^^^^^^^^^^^^^^^^^^
  File "D:\micromamba\envs\trellis\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\micromamba\envs\trellis\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\micromamba\envs\trellis\Lib\site-packages\torch\nn\modules\linear.py", line 125, in forward
    return F.linear(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1374x384 and 1024x2048)

**Comment by if-ai** [comment]
What's the device you are using,  the dino model version and the texture
res you selected?

**Comment by gsgoldma** [comment]
After I read your comment, I went through all the dinos, and I got Vitl to work. Texture size I'm using now is 1024. But all the rest throw me errors.

**Comment by if-ai** [comment]
I am not super sure but I think the others need to match the res of the texture resolution maybe you can go higher but not smaller probably I should remove ViT S and B
384 for ViT-S.
768 for ViT-B.
1024 for ViT-L.
1536 for ViT-g.

**Comment by if-ai** [comment]
I only allow big models until I am sure what is happening here
