### ISSUE TITLE
IndexError: pop from empty list

### ISSUE THREAD

**Issue by EightiesPower** [if-ai/ComfyUI-IF_Trellis#24]
I get this error when running the Image to 3D node. I have a manual Comfy installation and followed all the installation steps, although I didn't manage to set up xformers.

Error in image_to_3d: pop from empty list
Traceback (most recent call last):
  File "G:\Comfy_New\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\IF_Trellis.py", line 316, in image_to_3d
    outputs = model.run_multi_image(
              ^^^^^^^^^^^^^^^^^^^^^^
  File "G:\micromamba\envs\envs\ComfyUI\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "G:\Comfy_New\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\pipelines\trellis_image_to_3d.py", line 513, in run_multi_image
    coords = self.sample_sparse_structure(cond, num_samples, sparse_structure_sampler_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\micromamba\envs\envs\ComfyUI\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "G:\Comfy_New\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\pipelines\trellis_image_to_3d.py", line 285, in sample_sparse_structure
    z_s = self.sparse_structure_sampler.sample(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\micromamba\envs\envs\ComfyUI\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "G:\Comfy_New\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\pipelines\samplers\flow_euler.py", line 199, in sample
    return super().sample(model, noise, cond, steps, rescale_t, verbose, neg_cond=neg_cond, cfg_strength=cfg_strength, cfg_interval=cfg_interval, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\micromamba\envs\envs\ComfyUI\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "G:\Comfy_New\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\pipelines\samplers\flow_euler.py", line 112, in sample
    out = self.sample_once(model, sample, t, t_prev, cond, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\micromamba\envs\envs\ComfyUI\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "G:\Comfy_New\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\pipelines\samplers\flow_euler.py", line 73, in sample_once
    pred_x_0, pred_eps, pred_v = self._get_model_prediction(model, x_t, t, cond, **kwargs)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Comfy_New\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\pipelines\samplers\flow_euler.py", line 43, in _get_model_prediction
    pred_v = self._inference_model(model, x_t, t, cond, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Comfy_New\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\pipelines\trellis_image_to_3d.py", line 455, in _new_inference_model
    return self._old_inference_model(model, x_t, t, cond=cond_i, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Comfy_New\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\pipelines\trellis_image_to_3d.py", line 455, in _new_inference_model
    return self._old_inference_model(model, x_t, t, cond=cond_i, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Comfy_New\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\pipelines\trellis_image_to_3d.py", line 455, in _new_inference_model
    return self._old_inference_model(model, x_t, t, cond=cond_i, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 9 more times]
  File "G:\Comfy_New\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\pipelines\trellis_image_to_3d.py", line 453, in _new_inference_model
    cond_idx = cond_indices.pop(0)
               ^^^^^^^^^^^^^^^^^^^
IndexError: pop from empty list

!!! Exception during processing !!! pop from empty list
Traceback (most recent call last):
  File "G:\Comfy_New\ComfyUI\execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Comfy_New\ComfyUI\execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Comfy_New\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "G:\Comfy_New\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\micromamba\envs\envs\ComfyUI\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "G:\Comfy_New\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\IF_Trellis.py", line 316, in image_to_3d
    outputs = model.run_multi_image(
              ^^^^^^^^^^^^^^^^^^^^^^
  File "G:\micromamba\envs\envs\ComfyUI\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "G:\Comfy_New\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\pipelines\trellis_image_to_3d.py", line 513, in run_multi_image
    coords = self.sample_sparse_structure(cond, num_samples, sparse_structure_sampler_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\micromamba\envs\envs\ComfyUI\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "G:\Comfy_New\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\pipelines\trellis_image_to_3d.py", line 285, in sample_sparse_structure
    z_s = self.sparse_structure_sampler.sample(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\micromamba\envs\envs\ComfyUI\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "G:\Comfy_New\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\pipelines\samplers\flow_euler.py", line 199, in sample
    return super().sample(model, noise, cond, steps, rescale_t, verbose, neg_cond=neg_cond, cfg_strength=cfg_strength, cfg_interval=cfg_interval, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\micromamba\envs\envs\ComfyUI\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "G:\Comfy_New\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\pipelines\samplers\flow_euler.py", line 112, in sample
    out = self.sample_once(model, sample, t, t_prev, cond, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\micromamba\envs\envs\ComfyUI\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "G:\Comfy_New\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\pipelines\samplers\flow_euler.py", line 73, in sample_once
    pred_x_0, pred_eps, pred_v = self._get_model_prediction(model, x_t, t, cond, **kwargs)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Comfy_New\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\pipelines\samplers\flow_euler.py", line 43, in _get_model_prediction
    pred_v = self._inference_model(model, x_t, t, cond, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Comfy_New\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\pipelines\trellis_image_to_3d.py", line 455, in _new_inference_model
    return self._old_inference_model(model, x_t, t, cond=cond_i, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Comfy_New\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\pipelines\trellis_image_to_3d.py", line 455, in _new_inference_model
    return self._old_inference_model(model, x_t, t, cond=cond_i, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Comfy_New\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\pipelines\trellis_image_to_3d.py", line 455, in _new_inference_model
    return self._old_inference_model(model, x_t, t, cond=cond_i, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 9 more times]
  File "G:\Comfy_New\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\pipelines\trellis_image_to_3d.py", line 453, in _new_inference_model
    cond_idx = cond_indices.pop(0)
               ^^^^^^^^^^^^^^^^^^^
IndexError: pop from empty list

**Comment by EightiesPower** [comment]
Ok, so this error occurred in the multi image workflow, I've tried a single image workflow and it worked. Now the multi image workflow seems to work too, although the results aren't great. How many images should one use for this one? Is two enough?

**Comment by if-ai** [comment]
I recomeend 3 images and they must be same size the node does an automatic resizing to ensure they can work as a batch tensor but the node assumes you are using a traditional character/model sheet  or like if you take pictures of a real object the camera distance should be about the same and a frotal or 3quarter vie a back 3/4 view and a side view. 
The batch output in IF load images S should be connected to the image input of trellis node 
I haven't had a chance to check this error but I guess is happening because of the images you are usng are less tahn ideal and this thing is a bit tricky
