### ISSUE TITLE
Error loading TRELLIS model: HTTP Error 401: Unauthorized

### ISSUE THREAD

**Issue by TurningTide** [if-ai/ComfyUI-IF_Trellis#9]
spent lots of time installing-reinstalling torch and flash-attn. 
but now, when all errors are fixed - i get this one:

```
Model path after ensuring existence: E:\_AI\ComfyUI_N\models\checkpoints\TRELLIS-image-large
Path exists: True
Loading local model: ss_dec_conv3d_16l8_fp16
[SPARSE][CONV] spconv algo: native
Loading local model: ss_flow_img_dit_L_16l8_fp16
[ATTENTION] Using backend: flash_attn
Loading local model: slat_dec_gs_swin8_B_64l8gs32_fp16
Loading local model: slat_dec_rf_swin8_B_64l8r16_fp16
Loading local model: slat_dec_mesh_swin8_B_64l8m256c_fp16
Loading local model: slat_flow_img_dit_L_64l8p2_fp16
Error loading TRELLIS model: HTTP Error 401: Unauthorized
!!! Exception during processing !!! HTTP Error 401: Unauthorized
Traceback (most recent call last):
  File "E:\_AI\ComfyUI_N\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\_AI\ComfyUI_N\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\_AI\ComfyUI_N\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\_AI\ComfyUI_N\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\_AI\ComfyUI_N\custom_nodes\ComfyUI-IF_Trellis\IF_TrellisCheckpointLoader.py", line 164, in load_model
    pipeline = TrellisImageTo3DPipeline.from_pretrained(str(self.model_path))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\_AI\ComfyUI_N\custom_nodes\ComfyUI-IF_Trellis\trellis\pipelines\trellis_image_to_3d.py", line 73, in from_pretrained
    new_pipeline._init_image_cond_model(args['image_cond_model'])
  File "E:\_AI\ComfyUI_N\custom_nodes\ComfyUI-IF_Trellis\trellis\pipelines\trellis_image_to_3d.py", line 81, in _init_image_cond_model
    dinov2_model = torch.hub.load('facebookresearch/dinov2', name, pretrained=True)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

model is manually cloned into `models\checkpoints\TRELLIS-image-large`
HF_TOKEN env var present and valid

**Comment by TurningTide** [comment]
fixed by setting GITHUB_TOKEN env var
